version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: bankuser
      MYSQL_ROOT_PASSWORD: bankuser
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  mybank-app:
    image: mybank-image
    container_name: mybank-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

